Catch ClassNotFoundException, which is different than NoClassDefFoundError.  See http://javarevisited.blogspot.com/2011/07/classnotfoundexception-vs.html