If deleteProperty cannot find the property, then we now assume that it has been deleted and no longer throw an exception.
For example, The Kieler layout mechanism sometimes optimizes away _layoutHints.

To replicate:
  $PTII/bin/vergil ~/ptII/ptolemy/moml/demo/modulation.xml
  Graph -> Automatic Layout
  Undo, Redo, Undo

Formerly, _layoutHints was causing an error:
ptolemy.kernel.util.InternalErrorException: ChangeRequest failed (NOTE: there is no ChangeListener):
<group>
   <deleteProperty name="_layoutHint" />
</group>

Now, with this change the problem does not occur.

Tests in ptolemy/vergil/basic/layout/kieler/test/junit test for this.

See also
http://rtsys.informatik.uni-kiel.de/trac/kieler/ticket/1629