Array_new(): Don't cast to a Token here, the MS VisualC compiler fails: bash-2.05b$ cl Sequence.c Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 12.00.8168 for 80x86 Copyright (C) Microsoft Corp 1984-1998. All rights reserved.
Sequence.c
Sequence.c(182) : error C2440: 'type cast' : cannot convert from
'struct token ' to 'struct token '