endElement(): If we are processing a configure element, then catch NoClassDefFoundError and proceed.  The reason is that if we are running the automatic tests under JDK1.2.2 under Solaris then we will see errors like java.lang.NoClassDefFoundError: diva/canvas/Figure